import type { NewsPayload, SpectrumBucket } from './types'

export const bucketLabels: Record<SpectrumBucket, string> = {
  left: 'Progressista',
  centerLeft: 'Centro-progressista',
  center: 'Centro',
  centerRight: 'Centro-conservador',
  right: 'Conservador',
  unknown: 'Não classificado',
}

export const bucketColors: Record<SpectrumBucket, string> = {
  left: '#6d5dfc',
  centerLeft: '#3698db',
  center: '#31b58f',
  centerRight: '#f2a93b',
  right: '#e45b5b',
  unknown: '#a4a8b3',
}

export const mockNewsData: NewsPayload = {
  generatedAt: new Date().toISOString(),
  version: '0.1.0-demo',
  source: 'Coleta editorial · dados demonstrativos baseados no schema do scraper',
  stats: {
    clusterCount: 6,
    articleCount: 47,
    knownSources: 31,
    unknownSources: 7,
  },
  sources: [
    { name: 'Brasil 247', domain: 'brasil247.com', spectrumScore: 1, bucket: 'left', label: 'Progressista', confidence: 'manual', region: 'nacional', type: 'digital' },
    { name: 'CartaCapital', domain: 'cartacapital.com.br', spectrumScore: 2, bucket: 'left', label: 'Progressista', confidence: 'manual', region: 'nacional', type: 'revista' },
    { name: 'BBC News Brasil', domain: 'bbc.com', spectrumScore: 3, bucket: 'centerLeft', label: 'Centro-progressista', confidence: 'manual', region: 'internacional', type: 'jornal' },
    { name: 'Agência Brasil', domain: 'agenciabrasil.ebc.com.br', spectrumScore: 4, bucket: 'centerLeft', label: 'Institucional', confidence: 'manual', region: 'nacional', type: 'agência pública' },
    { name: 'G1', domain: 'g1.globo.com', spectrumScore: 5, bucket: 'center', label: 'Centro', confidence: 'manual', region: 'nacional', type: 'portal' },
    { name: 'CNN Brasil', domain: 'cnnbrasil.com.br', spectrumScore: 5, bucket: 'center', label: 'Centro', confidence: 'manual', region: 'nacional', type: 'tv/portal' },
    { name: 'Estadão', domain: 'estadao.com.br', spectrumScore: 6, bucket: 'centerRight', label: 'Centro-conservador', confidence: 'manual', region: 'nacional', type: 'jornal' },
    { name: 'Poder360', domain: 'poder360.com.br', spectrumScore: 6, bucket: 'centerRight', label: 'Centro-conservador', confidence: 'manual', region: 'nacional', type: 'digital' },
    { name: 'Gazeta do Povo', domain: 'gazetadopovo.com.br', spectrumScore: 8, bucket: 'right', label: 'Conservador', confidence: 'manual', region: 'nacional', type: 'jornal' },
    { name: 'Jovem Pan', domain: 'jovempan.com.br', spectrumScore: 9, bucket: 'right', label: 'Conservador', confidence: 'manual', region: 'nacional', type: 'rádio/portal' },
  ],
  clusters: [
    {
      id: 'story-stf-marco-temporal',
      storyUrl: 'https://news.google.com/stories/demo-stf-marco-temporal',
      title: 'STF retoma julgamento sobre marco temporal e reacende disputa no Congresso',
      summary: 'Veículos destacam efeitos jurídicos, reação de ruralistas e pressão de organizações indígenas. O cluster mostra alta amplitude editorial e divergência no enquadramento das manchetes.',
      topic: 'Política · Justiça',
      topicKeywords: ['stf', 'marco', 'temporal', 'congresso', 'indígenas'],
      imageUrl: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=1200&q=80',
      publishedAt: '2026-05-21T08:05:00Z',
      updatedAt: '2026-05-21T11:20:00Z',
      spectrum: { min: 1, max: 9, average: 5.3, knownCount: 9, unknownCount: 2, buckets: { left: 2, centerLeft: 1, center: 3, centerRight: 2, right: 1, unknown: 2 } },
      scores: { coverageDiversity: 92, spectrumBalance: 78, headlineDivergence: 66, confidence: 84 },
      flags: ['Alta cobertura', 'Manchetes divergentes', 'Amplitude editorial 1–9'],
      articles: [
        { id: 'a1', title: 'STF retoma julgamento sobre marco temporal nesta semana', description: 'Supremo volta a analisar recursos relacionados à tese.', url: '#', source: 'G1', sourceDomain: 'g1.globo.com', publishedAt: '2026-05-21T08:05:00Z', postedLabel: 'há 3 horas', bucket: 'center', spectrumScore: 5 },
        { id: 'a2', title: 'Marco temporal volta ao STF sob pressão do Congresso', description: 'Parlamentares articulam reação caso decisão avance.', url: '#', source: 'Estadão', sourceDomain: 'estadao.com.br', publishedAt: '2026-05-21T08:30:00Z', postedLabel: 'há 3 horas', bucket: 'centerRight', spectrumScore: 6 },
        { id: 'a3', title: 'Julgamento pode afetar direitos indígenas em todo o país', description: 'Entidades acompanham sessão com preocupação.', url: '#', source: 'Brasil 247', sourceDomain: 'brasil247.com', publishedAt: '2026-05-21T09:10:00Z', postedLabel: 'há 2 horas', bucket: 'left', spectrumScore: 1 },
        { id: 'a4', title: 'Ruralistas veem insegurança jurídica em julgamento no Supremo', description: 'Setor produtivo cobra definição do Congresso.', url: '#', source: 'Gazeta do Povo', sourceDomain: 'gazetadopovo.com.br', publishedAt: '2026-05-21T09:50:00Z', postedLabel: 'há 2 horas', bucket: 'right', spectrumScore: 8 },
      ],
    },
    {
      id: 'story-bc-juros',
      storyUrl: 'https://news.google.com/stories/demo-bc-juros',
      title: 'Banco Central mantém juros e mercado revisa projeções para inflação',
      summary: 'A cobertura se concentra em impacto econômico, reação do governo e leitura do mercado financeiro. Fontes econômicas dominam o cluster.',
      topic: 'Economia',
      topicKeywords: ['banco', 'central', 'juros', 'inflação', 'mercado'],
      imageUrl: 'https://images.unsplash.com/photo-1604594849809-dfedbc827105?auto=format&fit=crop&w=1200&q=80',
      publishedAt: '2026-05-21T07:15:00Z',
      updatedAt: '2026-05-21T10:40:00Z',
      spectrum: { min: 4, max: 7, average: 5.6, knownCount: 8, unknownCount: 1, buckets: { left: 0, centerLeft: 1, center: 4, centerRight: 3, right: 0, unknown: 1 } },
      scores: { coverageDiversity: 68, spectrumBalance: 58, headlineDivergence: 31, confidence: 88 },
      flags: ['Cobertura econômica', 'Baixa divergência'],
      articles: [
        { id: 'b1', title: 'BC mantém Selic e cita riscos para inflação', description: 'Comitê vê cenário externo ainda incerto.', url: '#', source: 'CNN Brasil', sourceDomain: 'cnnbrasil.com.br', publishedAt: '2026-05-21T07:15:00Z', postedLabel: 'há 4 horas', bucket: 'center', spectrumScore: 5 },
        { id: 'b2', title: 'Mercado reduz aposta em cortes após decisão do Banco Central', description: 'Economistas revisam expectativas para o ano.', url: '#', source: 'InfoMoney', sourceDomain: 'infomoney.com.br', publishedAt: '2026-05-21T08:00:00Z', postedLabel: 'há 3 horas', bucket: 'center', spectrumScore: 5 },
        { id: 'b3', title: 'Governo cobra cautela do BC em ciclo de juros', description: 'Integrantes do Planalto avaliam comunicado.', url: '#', source: 'Poder360', sourceDomain: 'poder360.com.br', publishedAt: '2026-05-21T08:44:00Z', postedLabel: 'há 2 horas', bucket: 'centerRight', spectrumScore: 6 },
      ],
    },
    {
      id: 'story-chuvas-sul',
      storyUrl: 'https://news.google.com/stories/demo-chuvas-sul',
      title: 'Chuvas fortes deixam cidades em alerta no Sul; Defesa Civil amplia monitoramento',
      summary: 'Cluster com forte presença de fontes regionais e institucionais, útil para acompanhar atualizações de serviço e impactos locais.',
      topic: 'Brasil · Clima',
      topicKeywords: ['chuvas', 'sul', 'defesa', 'civil', 'alerta'],
      imageUrl: 'https://images.unsplash.com/photo-1519692933481-e162a57d6721?auto=format&fit=crop&w=1200&q=80',
      publishedAt: '2026-05-21T06:20:00Z',
      updatedAt: '2026-05-21T11:05:00Z',
      spectrum: { min: 4, max: 5, average: 4.7, knownCount: 5, unknownCount: 6, buckets: { left: 0, centerLeft: 2, center: 3, centerRight: 0, right: 0, unknown: 6 } },
      scores: { coverageDiversity: 44, spectrumBalance: 39, headlineDivergence: 24, confidence: 62 },
      flags: ['Muitas fontes regionais não classificadas', 'Serviço público'],
      articles: [
        { id: 'c1', title: 'Defesa Civil alerta para risco de alagamentos no Sul', description: 'Órgãos estaduais monitoram áreas vulneráveis.', url: '#', source: 'Agência Brasil', sourceDomain: 'agenciabrasil.ebc.com.br', publishedAt: '2026-05-21T06:20:00Z', postedLabel: 'há 5 horas', bucket: 'centerLeft', spectrumScore: 4 },
        { id: 'c2', title: 'Cidades do RS registram transtornos após temporal', description: 'Prefeituras abrem pontos de apoio.', url: '#', source: 'GZH', sourceDomain: 'gauchazh.clicrbs.com.br', publishedAt: '2026-05-21T07:00:00Z', postedLabel: 'há 4 horas', bucket: 'center', spectrumScore: 5 },
      ],
    },
    {
      id: 'story-operacao-pf',
      storyUrl: 'https://news.google.com/stories/demo-operacao-pf',
      title: 'Polícia Federal faz operação contra fraudes em contratos públicos',
      summary: 'A cobertura divide foco entre detalhes da investigação, reação política e impacto administrativo. Há cobertura concentrada em portais nacionais.',
      topic: 'Justiça · Política',
      topicKeywords: ['polícia', 'federal', 'fraudes', 'contratos', 'operação'],
      imageUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=1200&q=80',
      publishedAt: '2026-05-21T09:00:00Z',
      updatedAt: '2026-05-21T11:50:00Z',
      spectrum: { min: 2, max: 8, average: 5.9, knownCount: 7, unknownCount: 1, buckets: { left: 1, centerLeft: 0, center: 2, centerRight: 3, right: 1, unknown: 1 } },
      scores: { coverageDiversity: 76, spectrumBalance: 61, headlineDivergence: 52, confidence: 79 },
      flags: ['Cobertura concentrada no centro-direita', 'Investigação em andamento'],
      articles: [
        { id: 'd1', title: 'PF mira suspeitos de fraude em contratos públicos', description: 'Mandados são cumpridos em três estados.', url: '#', source: 'Metrópoles', sourceDomain: 'metropoles.com', publishedAt: '2026-05-21T09:00:00Z', postedLabel: 'há 2 horas', bucket: 'center', spectrumScore: 5 },
        { id: 'd2', title: 'Operação expõe fragilidade em compras governamentais', description: 'Especialistas cobram aperfeiçoamento de controles.', url: '#', source: 'Estadão', sourceDomain: 'estadao.com.br', publishedAt: '2026-05-21T09:30:00Z', postedLabel: 'há 2 horas', bucket: 'centerRight', spectrumScore: 6 },
      ],
    },
    {
      id: 'story-saude-vacina',
      storyUrl: 'https://news.google.com/stories/demo-saude-vacina',
      title: 'Ministério da Saúde anuncia nova campanha de vacinação em capitais',
      summary: 'Fontes institucionais e grandes portais destacam calendário, público-alvo e logística. Baixa polarização e alta utilidade pública.',
      topic: 'Saúde',
      topicKeywords: ['saúde', 'vacinação', 'campanha', 'capitais', 'ministério'],
      imageUrl: 'https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=1200&q=80',
      publishedAt: '2026-05-21T05:45:00Z',
      updatedAt: '2026-05-21T09:15:00Z',
      spectrum: { min: 3, max: 6, average: 4.8, knownCount: 6, unknownCount: 2, buckets: { left: 0, centerLeft: 2, center: 3, centerRight: 1, right: 0, unknown: 2 } },
      scores: { coverageDiversity: 61, spectrumBalance: 53, headlineDivergence: 18, confidence: 86 },
      flags: ['Utilidade pública', 'Baixa divergência'],
      articles: [
        { id: 'e1', title: 'Saúde lança campanha de vacinação em capitais', description: 'Pasta divulga público-alvo e calendário.', url: '#', source: 'Agência Brasil', sourceDomain: 'agenciabrasil.ebc.com.br', publishedAt: '2026-05-21T05:45:00Z', postedLabel: 'há 6 horas', bucket: 'centerLeft', spectrumScore: 4 },
        { id: 'e2', title: 'Veja quem pode se vacinar na nova etapa da campanha', description: 'Capitais terão pontos extras no fim de semana.', url: '#', source: 'G1', sourceDomain: 'g1.globo.com', publishedAt: '2026-05-21T07:20:00Z', postedLabel: 'há 4 horas', bucket: 'center', spectrumScore: 5 },
      ],
    },
    {
      id: 'story-politica-fiscal',
      storyUrl: 'https://news.google.com/stories/demo-politica-fiscal',
      title: 'Debate fiscal opõe governo e oposição antes de votação no Congresso',
      summary: 'Cluster político-econômico com grande variação de enquadramento: responsabilidade fiscal, gasto público e impacto social aparecem como ângulos concorrentes.',
      topic: 'Política · Economia',
      topicKeywords: ['fiscal', 'governo', 'oposição', 'congresso', 'gastos'],
      imageUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80',
      publishedAt: '2026-05-21T10:05:00Z',
      updatedAt: '2026-05-21T12:00:00Z',
      spectrum: { min: 1, max: 10, average: 6.1, knownCount: 10, unknownCount: 1, buckets: { left: 2, centerLeft: 1, center: 2, centerRight: 2, right: 3, unknown: 1 } },
      scores: { coverageDiversity: 95, spectrumBalance: 73, headlineDivergence: 81, confidence: 82 },
      flags: ['Alta divergência', 'Todos os buckets representados'],
      articles: [
        { id: 'f1', title: 'Governo negocia texto fiscal antes de votação decisiva', description: 'Líderes buscam acordo para reduzir resistências.', url: '#', source: 'Poder360', sourceDomain: 'poder360.com.br', publishedAt: '2026-05-21T10:05:00Z', postedLabel: 'há 1 hora', bucket: 'centerRight', spectrumScore: 6 },
        { id: 'f2', title: 'Oposição vê risco de aumento de gastos em projeto fiscal', description: 'Parlamentares cobram trava mais rígida.', url: '#', source: 'Jovem Pan', sourceDomain: 'jovempan.com.br', publishedAt: '2026-05-21T10:20:00Z', postedLabel: 'há 1 hora', bucket: 'right', spectrumScore: 9 },
        { id: 'f3', title: 'Texto fiscal pode preservar investimentos sociais', description: 'Aliados defendem margem para programas prioritários.', url: '#', source: 'CartaCapital', sourceDomain: 'cartacapital.com.br', publishedAt: '2026-05-21T10:35:00Z', postedLabel: 'há 1 hora', bucket: 'left', spectrumScore: 2 },
      ],
    },
  ],
}
